CREATE SCHEMA ERRORSYSTEM;
USE ERRORSYSTEM;

CREATE TABLE ERROS (
	Id INT PRIMARY KEY AUTO_INCREMENT, 
    Nome VARCHAR(255) NOT NULL,
    Descricao VARCHAR(255),
    Plataforma VARCHAR(255),
    Resolucao VARCHAR(255)
);
